### ISSUE TITLE
Maybe make the document more clear when using with bzlmod

### ISSUE THREAD

**Issue by mzhaom** [bazel-contrib/rules_jsonnet#195]
I'm new to bzlmod, somehow this is what should be done to use this with bzlmod:

Add to MODEL.bazel:
```
bazel_dep(name = "rules_jsonnet", version = "0.6.0")
```

In BUILD.bazel
```
load("@rules_jsonnet//jsonnet:jsonnet.bzl", "jsonnet_library", "jsonnet_to_json")
```

Note normally it was `@io_bazel_rules_jsonnet//jsonnet:jsonnet.bzl` based on the name specified in the http_archive

**Comment by EdSchouten** [comment]
Hey there!
I'm going to close this, because this is now already covered. Support for WORKSPACE has been removed, meaning that all references in this repo now use `@rules_jsonnet` instead of `@io_bazel_rules_jsonnet`. Thanks for reporting this regardless!
